database:
  file: "coins.db"

webstore:
  endpoint: "https://arsyanet.site/api.php"
  user-agent: "Bedrock-Server"
  timeout-ms: 5000
  check-on-proxy-login: true

internal-api:
  host: "127.0.0.1"
  port: 37841
  token: "ganti-token-internal-ini"

messages:
  currency-name: "Arsya Premium Coin"

logging:
  verbose: false
